name: 'DemoJSAction'
description: 'Display message'
inputs:
  name-of-you:
    decription: 'Your name'
    required: true
    default: 'Kriti'
outputs:
  time:
    description: 'The time of the message'
runs:
  using: 'node12'
  main: 'dist/index.js'
icon: 'airplay'
color: 'blue'
